name: qrio_smart
description: A new smart Flutter project for QR code generation and scanning.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
